# Generated by Django 4.2.8 on 2024-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('P', 'pending'), ('C', 'complete'), ('F', 'failed')], default='F', max_length=50),
        ),
    ]
