# Generated by Django 4.2.8 on 2024-05-11 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_chatmessages_options_alter_chatmessages_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
